import {
  FORUM_TITLE,
  HOME_TITLE,
  KNOWLEDGE_ZONE_TITLE,
  LOG_IN_TITLE,
} from "./titles";
import { HOME_URL, LOG_IN_URL, KNOWLEDGE_ZONE_URL, FORUM_URL } from "./urls";

export const publicNavItems = [
  // { title: HOME_TITLE, href: HOME_URL },
  { title: LOG_IN_TITLE, href: LOG_IN_URL },
  { title: KNOWLEDGE_ZONE_TITLE, href: KNOWLEDGE_ZONE_URL },
  { title: FORUM_TITLE, href: FORUM_URL },
];

// const adminNavItems = {
//     {HOME_TITLE, HOME_URL},
//     {APARTMENTS_TITLE, APARTMENTS_ID},
//     {BOOK_APARTMENT_TITLE, BOOK_APARTMENT_ID},
//     {LOCATION_TITLE, LOCATION_ID},
//     {GALLERY_TITLE, GALLERY_ID},
//     {SALE_OF_APARTMENTS_TITLE, SALE_OF_APARTMENTS_ID},
//     {ABOUT_THE_INVESTOR_TITLE, ABOUT_THE_INVESTOR_ID},
//   };

// const visitorNavItems = {
//     {HOME_TITLE, HOME_URL},
//     {APARTMENTS_TITLE, APARTMENTS_ID},
//     {BOOK_APARTMENT_TITLE, BOOK_APARTMENT_ID},
//     {LOCATION_TITLE, LOCATION_ID},
//     {GALLERY_TITLE, GALLERY_ID},
//     {SALE_OF_APARTMENTS_TITLE, SALE_OF_APARTMENTS_ID},
//     {ABOUT_THE_INVESTOR_TITLE, ABOUT_THE_INVESTOR_ID},
//   };
